version: '3'

services:
  frontend:
    build: ./app/frontend/
    user: node
    container_name: expo_web
    command: web
    restart: always
    volumes:
      - ./app/frontend:/home/app
    ports:
      - 3000:19006
      - 3004:19000
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - ENDPOINT=3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  backend:
    build: ./app/backend/
    user: node
    container_name: blogs_api
    restart: always
    volumes:
      - ./app/backend:/home/node/app
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_PORT: 3001
      DATABASE_URL: mysql://root:root@db:3306/blogs_api
      JWT_SECRET: jwtAPIsecret
      NODE_ENV: 'development'
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  
  db:
    image: mysql:8.0.30
    container_name: blogs_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3002:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogs_api
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5